<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Xunit.DependencyInjection" />
    <PackageReference Include="Xunit.DependencyInjection.Logging" />
    <!-- remove direct xunit reference (it generates code with direct link) -->
    <PackageReference Remove="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="testsettings*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
