name: Comments
concurrency:
  group: comments-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: write-all
defaults:
  run:
    shell: bash
on:
  issue_comment:
    types: [created]
jobs:
  pre:
    name: Initialize
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') && github.event.sender.login == 'vchirikov' }}
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.gh.outputs.sha }}
      branch: ${{ steps.gh.outputs.branch }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          clean: false
          fetch-depth: 0

      - name: Checkout Pull Request
        if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: git rev-parse
        id: gh
        run: |
          sha=$(git rev-parse HEAD);
          branch=$(git rev-parse --abbrev-ref HEAD);
          echo -e "\033[38;5;113;48;5;16m sha: $sha \033[0m"
          echo -e "\033[38;5;113;48;5;16m branch: $branch \033[0m"
          echo "::set-output name=sha::$sha"
          echo "::set-output name=branch::$branch"

  unit-tests-workflow-job:
    name: /unit-tests
    if: ${{ startsWith(github.event.comment.body, '/unit-test') }}
    needs: pre
    secrets: inherit
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ needs.pre.outputs.branch }}

  publish-workflow-job:
    name: /publish
    if: ${{ startsWith(github.event.comment.body, '/publish') }}
    needs: pre
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ needs.pre.outputs.branch }}
