name: Tests
concurrency:
  group: tests-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: write-all
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
env:
  DOCKER_BUILDKIT: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "true"
  DOTNET_CLI_UI_LANGUAGE: en-US
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_SVCUTIL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_ROLL_FORWARD: Major
  DOTNET_ROLL_FORWARD_TO_PRERELEASE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  POWERSHELL_TELEMETRY_OPTOUT: 1
  POWERSHELL_UPDATECHECK_OPTOUT: 1
jobs:
  tests:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/unit-test') && github.event.sender.login == 'vchirikov') }}
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0

      - name: Checkout Pull Request
        if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') }}
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save & forward default env variables
        run: |
          env | grep -E '^(GITHUB_|CI)' >> $GITHUB_ENV

      - name: Generate version variables
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: Print info
        run: |
          echo "Triggered on ${{ github.event_name }}"
          echo "SemVer2 ${{ steps.nbgv.outputs.SemVer2 }}"
          echo "::add-matcher::./.github/csc.json"

      - name: NuGet cache restore
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet build
        id: build
        uses: vchirikov/.github/shell-and-report-action@master
        with:
          commands: |-
            dotnet build --nologo -c Debug -p:GenerateFullPaths=true /clp:NoSummary | sed -E 's/^(.*?)(error [A-Z0-9]{3,}:)(.*)$/- \1\2\3/g'
          report-start: |-
            :gear: Run unit-tests... `༼ つ ◕_◕ ༽つ`
          report-failure: |-
            ❌ Build failed  `(╯°□°)╯︵ ┻━┻`

            <details open> <summary> dotnet build output </summary>

            ```diff
            ${{ steps.build.outputs.out }}
            ```

            </details>

      - name: dotnet test
        id: tests
        uses: vchirikov/.github/shell-and-report-action@master
        with:
          commands: |-
            dotnet test --nologo --no-build --filter 'FullyQualifiedName~UnitTests' --blame-hang --blame-hang-timeout 60s --logger:"github;name=unit-tests;GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} | sed -E 's/^([[:space:]]+Failed [a-z_A-Z0-9]{3,})(.*)$/- \1\2/g'
          report-start: |-
            :gear: Run unit-tests... `༼ つ ◕_◕ ༽つ`
          report-success: |-
            ✅ Running unit tests on `${{ steps.nbgv.outputs.SemVer2 }}` version was successful!

            ${{ steps.tests.outputs.summary }}

            `(•_•)          ( •_•)>⌐■-■          (⌐■_■)`
          report-failure: |-
            ❌ Tests failed. `(╯°□°)╯︵ ┻━┻`

            ${{ steps.tests.outputs.summary }}

            <details open> <summary> Tests output </summary>

            ```diff
            ${{ steps.tests.outputs.out }}
            ```

            </details>

      - name: Report cancellation
        if: ${{ cancelled() }}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
          message: |
            ⚠️ Test run cancelled. `(ง •_•)ง`

      - name: Report failure
        if: ${{ failure() && steps.tests.outcome != 'failure' && steps.build.outcome != 'failure'}}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ❌ Failed. `( ˘︹˘ )`
