name: Tests
concurrency:
  group: tests-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: write-all
defaults:
  run:
    shell: bash
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: GITHUB_SHA ref to checkout and to link annotations to
        default: ""
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "true"
  DOTNET_CLI_UI_LANGUAGE: en-US
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_SVCUTIL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_ROLL_FORWARD: Major
  DOTNET_ROLL_FORWARD_TO_PRERELEASE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  POWERSHELL_TELEMETRY_OPTOUT: 1
  POWERSHELL_UPDATECHECK_OPTOUT: 1
jobs:
  dbg:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Dump job context
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
      - name: Dump steps context
        run: echo "$STEPS_CONTEXT"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
      - name: Dump runner context
        run: echo "$RUNNER_CONTEXT"
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
      - name: Dump strategy context
        run: echo "$STRATEGY_CONTEXT"
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      - name: Dump matrix context
        run: echo "$MATRIX_CONTEXT"
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: echo ref
        if: ${{ github.event_name == 'workflow_call' }}
        run: 'echo -e "\033[38;5;99;48;5;16m ref: ${{ inputs.ref }} \033[0m"'

      - name: git checkout / on 'workflow_call'
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/checkout@v3
        with:
          clean: false
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: git checkout / on non-'workflow_call'
        if: ${{ github.event_name != 'workflow_call' }}
        uses: actions/checkout@v3
        with:
          clean: false
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Save & forward default env variables
        id: gh
        run: |
          env | grep -E '^(GITHUB_|CI)' | grep -E GITHUB_SHA= --invert-match >> $GITHUB_ENV
          sha=$(git rev-parse HEAD)
          echo "GITHUB_SHA=$sha" >> $GITHUB_ENV
          echo "::set-output name=sha::$sha"
          echo "::add-matcher::./.github/csc.json"
          echo "##[add-matcher]$GITHUB_WORKSPACE/.github/csc.json"
          echo "##[add-matcher]./.github/csc.json"

      - name: Generate version variables
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: NuGet cache restore
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet build
        id: build
        uses: vchirikov/.github/shell-and-report-action@master
        with:
          commands: |-
            dotnet build --nologo -c Debug -p:GenerateFullPaths=true /clp:NoSummary | sed -E 's/^(.*?)(error [A-Z0-9]{3,}:)(.*)$/- \1\2\3/g'
          report-start: |-
            :gear: Run unit-tests... `༼ つ ◕_◕ ༽つ`
          report-failure: |-
            ❌ Build failed  `(╯°□°)╯︵ ┻━┻`

            <details open> <summary> dotnet build output </summary>

            ```diff
            {0}
            ```

            </details>

      - name: dotnet test
        id: tests
        uses: vchirikov/.github/shell-and-report-action@master
        with:
          commands: |-
            dotnet test --nologo --no-build --filter 'FullyQualifiedName~UnitTests' --blame-hang --blame-hang-timeout 60s --logger:"github;name=unit-tests;GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }};GITHUB_SHA=${{ steps.gh.outputs.sha }}" | sed -E 's/^([[:space:]]+Failed [a-z_A-Z0-9]{3,})(.*)$/- \1\2/g'

      - name: Report tests success
        if: ${{ steps.tests.outcome == 'success' }}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
          message: |
            ✅ Running unit tests on `${{ steps.nbgv.outputs.SemVer2 }}` version was successful!

            ${{ steps.tests.outputs.summary }}

            `(•_•)          ( •_•)>⌐■-■          (⌐■_■)`

      - name: Report tests failed
        if: ${{ failure() && steps.tests.outcome == 'failure' }}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
          message: |
            ❌ Tests failed. `(╯°□°)╯︵ ┻━┻`

            ${{ steps.tests.outputs.summary }}

            <details open> <summary> Tests output </summary>

            ```diff
            ${{ steps.tests.outputs.out }}
            ```

            </details>

      - name: Report cancellation
        if: ${{ cancelled() }}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
          message: |
            ⚠️ Test run cancelled. `(ง •_•)ง`

      - name: Report failure
        if: ${{ failure() && steps.tests.outcome != 'failure' && steps.build.outcome != 'failure'}}
        uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ❌ Failed. `( ˘︹˘ )`
